ALTER TABLE account ADD COLUMN profile_fields_json TEXT;
ALTER TABLE account ADD COLUMN locked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE account ADD COLUMN bot INTEGER NOT NULL DEFAULT 0;
ALTER TABLE account ADD COLUMN discoverable INTEGER NOT NULL DEFAULT 1;
ALTER TABLE account ADD COLUMN indexable INTEGER NOT NULL DEFAULT 1;

ALTER TABLE remote_profiles ADD COLUMN profile_fields_json TEXT;
