ALTER TABLE remote_profiles ADD COLUMN locked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE remote_profiles ADD COLUMN bot INTEGER NOT NULL DEFAULT 0;
ALTER TABLE remote_profiles ADD COLUMN discoverable INTEGER NOT NULL DEFAULT 1;
ALTER TABLE remote_profiles ADD COLUMN indexable INTEGER NOT NULL DEFAULT 1;
